### PR TITLE
fix display for number less than 100 satoshis

### PR DESCRIPTION
**Pull request by rnevet**
Replaced roundFloat with printFloat, now rounds and returns String with fixed precision.
Converted tabs to spaces.

### CODE REVIEW

**Comment by Evanito** [comment]
Works as expected, cleared to merge!

**Comment by rnevet** [comment]
Minor improvement:
Hide estimated earnings rows for coins with no active loans (sadly)

**Comment by rnevet** [comment]
@Kurairaito can you confirm that this fixed the issue you found?

**Comment by Kurairaito** [comment]
Yes it works,
Also the improvement to hide coin with no active loan works fine too

**Comment by rnevet** [comment]
Thanks!

**Pull request merged**
