### PR TITLE
higher nonce faktor to prevent "provided" error

### PR DESCRIPTION
**Pull request by martinkrung**
should fix this:

https://github.com/Mikadily/poloniexlendingbot/issues/36

for Python 2.7.9 on ubuntu

### CODE REVIEW

**Comment by Mikadily** [comment]
I'm not sure about it. Someone proposed it before and we agreed not to change nonce.
Here: https://github.com/Mikadily/poloniexlendingbot/pull/13

> Quote the documentation from Poloniex: "The nonce parameter is an integer which must always be greater than the previous nonce used".

Also pinging @bhaak

**Comment by martinkrung** [comment]
I am not sure if it  has to do with the api key, as in #13. My running lendingbot was stopping and after setting a higher nonce it worked again. this makes no sense, as my clock is not running backwards. but I have to admit, that I do sync my different computer and If I start the lendingbot on both and not having the exact same time set this can result in this error

**Comment by Webonaute** [comment]
I confiirm it not fixed the issue for me. I still have the error since 2 days

**Comment by Evanito** [comment]
I find that this issue (also issue #36 ) was caused for me by having multiple applications using the same API key. My recommendation is to delete all APIs and start over with one key per integration.

That fixed it for me.

**Pull request closed without merging**
