### PR TITLE
Add End Date

### PR DESCRIPTION
**Pull request by Evanito**
## Description

Allows user to add a date on which the bot will make sure all lends are done by.

Counts down the days on webpage, then automatically shuts down once it can no longer lend.

For users who want the bot to be done by a certain date. Recommended to give it 60 day notice so you don't get stuck with any super long lends.

Closes issue #14 

## TESTING STAGE

Tested with endDate set in the past, not set at all, set in the far future, and set tomorrow. Bot performed as expected in all cases. Bot deactivates at the first attempt to lend after midnight two days before enddate and leaves a message on the webpage.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] **I have read CONTRIBUTING.md**
- [x] **I fully understand [Github Flow.](https://guides.github.com/introduction/flow/)**
- [x] **My code adheres to the [code style of this project.] (https://poloniexlendingbot.readthedocs.io/en/latest/contributing.html)**
- [x] **I have updated the documentation in /docs if I have changed the config, arguments, logic in how the bot works, or anything that understandably needs a documentation change.**
- [x] **If my change requires a change to the config, I have updated the config file and command line arguments accordingly.**
- [x] **I have tested the bot with no issues for 24 continuous hours. If issues were experienced, they have been patched and tested again.**

### CODE REVIEW

**Comment by rnevet** [comment]
Nice, needs a bit of testing I think.

**Comment by Evanito** [comment]
@rnevet Okay I think this feature is done as far as I will go with it. Any changes you want or does it look good?

**Comment by Evanito** [comment]
Ugh, 15 commits. Need to keep it shorter in the future. Good thing we squash & merge. :^)

@rnevet Please review

**Comment by Evanito** [comment]
Has worked fine for me with no errors for 24 hours and over multiple use cases. Merging.

**Comment by Evanito** [comment]
LGTM

**Pull request merged**
