### PR TITLE
Dynamically increase limit of returnLoanOrders request

### PR DESCRIPTION
**Pull request by rnevet**
This will prevent maxDailyRate loans because bot doesn't retrieve the entire loan list

### CODE REVIEW

**Comment by Mikadily** [comment]
I'm trying to digest. Can you briefly explain how you decide to increase the limit?

**Comment by rnevet** [comment]
Basically if you reach the end of the offers and you are under the limit, it means you have seen all offers. and you can send at maxDailyRate. Otherwise there are more offers that you can fetch -> increase limit and repeat.

**Comment by Mikadily** [comment]
Ok. I forgot, what's the default limit, 200? What if the lendbook size is exactly equal default limit?

**Comment by rnevet** [comment]
Than it will increase once, no harm done.

**Comment by rnevet** [comment]
The increase process is permanent per coin and per bot run... after it increases the bot will use that limit for the specific coin until it is restarted. (The idea at least)

**Comment by Mikadily** [comment]
Ah. OK, interesting idea and looks good. I'll test and merge it. Hope in two days.

**Comment by rnevet** [comment]
I tested it by raising the minDailyRate to 0.1 so for example for BTC the bot raised the limit to ~800 offers before it decided to make a loan at 0.1.

**Comment by Mikadily** [comment]
I'm trying to think how to merge this, but it's a bit messy. Somehow it's intervened with your other commit (config file fix). Maybe you know a good way to squash it?
screenshot from 2016-05-05 16-57-19

**Comment by rnevet** [comment]
You can either  cherry pick the commit locally instead of merging...  
Or you can merge it locally and then squash if needed.

**Comment by rnevet** [comment]
Should I merge this change?
I can do the cherry picking.

**Comment by Mikadily** [comment]
Yeah, go for it @rnevet. I just didn't want all the "patch-1" crap in the commit message. Otherwise I'm happy with how it works.

**Comment by rnevet** [comment]
merged: https://github.com/Mikadily/poloniexlendingbot/commit/a81cbbdd71ee61ce28d0fb4866c4491ed2059788

**Pull request closed without merging**
