### PR TITLE
Further optimization for mobile

### PR DESCRIPTION
**Pull request by rnevet**

### CODE REVIEW

**Comment by rnevet** [comment]
@yura-pakhuchiy what do you think?

**Comment by yura-pakhuchiy** [comment]
@rnevet I like all changes, except `Month` -> `M`. It affects all resolutions smaller than 768x..., but not really necessary even on 320x.. screen (it can be displayed without scrolling). However M/W/D/H is harder to understand than Month/Week/etc.

The only resolution it makes sense is 240x... (really small screens), but if you want to support them, then all other fields should be fixed (because they generate vertical scrolling now). If you will do it, I suggest to add separate media query for <320x... devices for this changes.

**Comment by yura-pakhuchiy** [comment]
@rnevet In the first message, I missed that it also makes sense for non-BTC estimated earnings. I propose to apply new format only to non-BTC fields, but leave BTC fields with full form.

**Comment by yura-pakhuchiy** [comment]
BTW, it is easier to review if commit message lists changes in the commit. Especially if there are several in one commit.

**Comment by rnevet** [comment]
@Evanito @Mikadily

**Comment by rnevet** [comment]
@yura-pakhuchiy Please take a look into the last update.
I removed the Month->M change - the resolution change is defined by the bootstrap framework, I don't want to define all the CSS myself.

**Comment by yura-pakhuchiy** [comment]
@rnever I tested it already, looks good to me. Especially I like "add to home screen" feature and new icon. Great work!

**Comment by yura-pakhuchiy** [comment]
@rnevet I tested it already, looks good to me. Especially I like "add to home screen" feature and new icon. Great work!

**Comment by yura-pakhuchiy** [comment]
@rnevet BTW, what do you think about dropping table completely and using bootstrap's "col-xx-y" for formatting?

**Comment by rnevet** [comment]
@yura-pakhuchiy it's a good idea (I also thought about it), just don't have time to do it. If you can go for it.

**Comment by yura-pakhuchiy** [comment]
@rnevet minor glitch with new title bar: in local file mode it displays button over the status line

**Pull request merged**
