### PR TITLE
Run from anywhere without context issues

### LINKED ISSUE #172: Can't find *.cfg
Hello today i got following issue,

```
Obtaining settings from config file.
Traceback (most recent call last):
  File "bot/poloniexlendingbot-0.3/lendingbot.py", line 123, in <module>
    shutil.copy('default.cfg.example', 'default.cfg')
  File "/usr/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'default.cfg.example'
```

when im in the bot directory everything works fine...

### PR DESCRIPTION
**Pull request by Evanito**
Side note: why was config passed as a list of one?

## Description

Closes #172 and we won't get something like it again.

Checks the script's folder for all config files, instead of where it is run from. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] **I have read CONTRIBUTING.md**
- [x] **I fully understand [Github Flow.](https://guides.github.com/introduction/flow/)**
- [x] **My code adheres to the [code style of this project.](https://poloniexlendingbot.readthedocs.io/en/latest/contributing.html)**
- [N/A] **I have updated the documentation in /docs if I have changed the config, arguments, logic in how the bot works, or anything that understandably needs a documentation change.**
- [x] **I have updated the config file accordingly if my change requires a new configuration setting or changes an existing one.**
- [ ] **I have tested the bot with no issues for 24 continuous hours. If issues were experienced, they have been patched and tested again.**

### CODE REVIEW

**Comment by rnevet** [comment]
lgtm

**Comment by rnevet** [comment]
Regarding your side note, I'm assuming at some point the variable was initialized as a list - and when refactoring it was just passed as the same type.

**Comment by praeluceo** [comment]
This commit introduces a regression, executing lendingbot.py from within its CWD ironically fails, executing it from outside its own directory succeeds:

```
user@localhost:~/bots/poloniexlendingbot$ python lendingbot.py 
Traceback (most recent call last):
  File "lendingbot.py", line 15, in <module>
    os.chdir(os.path.dirname(sys.argv[0]))  # Allow relative paths
OSError: [Errno 2] No such file or directory: ''
user@localhost:~/bots/poloniexlendingbot$ ./lend^C
user@localhost:~/bots/poloniexlendingbot$ cd
user@localhost:~$ python bots/poloniexlendingbot/lendingbot.py 
Welcome to Poloniex Lending Bot
Started WebServer, lendingbot status available at http://localhost:8000/lendingbot.html
```

**Comment by Evanito** [comment]
I can not reproduce on windows.
Planned fix: try to open a relative file and change directory on except.

**Comment by Evanito** [comment]
@praeluceo A fix for this has been included in the lending-rewrite branch. I recommend you cherry-pick the commit if you only want to test it.

**Pull request merged**
