### PR TITLE
fix number display

### PR DESCRIPTION
**Pull request by Kurairaito**
fix display for number less than 100 satoshis displayed in scientific notation

### CODE REVIEW

**Comment by Kurairaito** [comment]
example : 

fix

same for highest bid (doge example)

**Comment by rnevet** [comment]
I think it would be better to improve roundFloat function.

**Comment by rnevet** [comment]
@Kurairaito 
My suggestion:
https://github.com/Mikadily/poloniexlendingbot/pull/79

**Comment by Evanito** [comment]
Works as expected, cleared to merge!

**Comment by Kurairaito** [comment]
Your suggestion doesn't works on my computer (win 10 up to date, neither edge nor chrome)

**Comment by Evanito** [comment]
@Kurairaito His suggestion works fine for me. Screencap?

PS: html files are independent of OS, and only slightly dependent on browser, so if it works for us it should work for you.

**Comment by rnevet** [comment]
@Kurairaito 
I basically built on your solution of adding toFixed and used in printFloat for every float, should work. 

Can you make sure that you checked out the correct branch "html_improvements" and javascript is updated?

**Comment by Kurairaito** [comment]
Here is an example from my phone
screenshot_20160614-131812

**Comment by rnevet** [comment]
@Kurairaito Thanks!
Corrected the implementation to include highestBid.

**Comment by rnevet** [comment]
Implemented in https://github.com/Mikadily/poloniexlendingbot/pull/79

**Pull request closed without merging**
