### PR TITLE
loop through all possible currencies

### PR DESCRIPTION
**Pull request by Kurairaito**
this branch allow you to display performance of all your currencies lended.
It will create a row for each currency found in json file. if for any reason you won't display a currency, you can remove it from var currencies = [ at line 42

### CODE REVIEW

**Comment by Kurairaito** [comment]
example : 
example

**Comment by rnevet** [comment]
I like the idea of displaying the actual predicted earnings (definitely an improvement) but:

1. I think  using regex to harvest the information back from the string status is a wrong approach, It would be better to log the raw data in the json log. (would need to extend the Logger)
2. Why did you hard code the coin letters into the HTML? should be possible to parse it without, split the currencies based on [ and then parse each for the coin name and values.

IMO improving the logging to include raw data would give more flexibility and room for improvements.

**Comment by Kurairaito** [comment]
Well I did it because it was easier. I could call poloniex api to grab currencies list also but it would bring more code and delay in retrieving data.

Improving logger seems also hard to me (doesn't have much knowlege in python)

**Comment by Evanito** [comment]
LGTM

**Comment by rnevet** [comment]
The improvement I suggested can be done later.

**Pull request merged**
