### PR TITLE
Improved logging with raw values

### PR DESCRIPTION
**Pull request by rnevet**
Added the ability to log raw status values (per coin) into the json log. (no need to perform regex on status strings to get values)
Added display of available funds and effective interest rate in lendingbot.html.

Should also give a solution to [Suggestion] Include unlended coins in real "Average Lending Rate" https://github.com/Mikadily/poloniexlendingbot/issues/40

### CODE REVIEW

**Comment by rnevet** [comment]
I updated the calculation of multiple days earning interest rate - compound interest, if I understand correctly multi days interest rate should be Math.pow(<daily_rate>, <days>) and not multiply by the days. As the interest is daily.

**Comment by Evanito** [comment]
LGTM :+1:

**Comment by rnevet** [comment]
Are you sure that Poloniex doesn't calculate compound interest? makes the term daily interest rate a bit misleading.

**Comment by Evanito** [comment]
No I don't know how Poloniex calculates "interest" but I assume it is simple daily, only compounding once the lend ends.

**Comment by rnevet** [comment]
I added the estimation of BTC earnings for Alt coins based on polo ticker.
Reverted to compound interest calculation.

**Comment by rnevet** [comment]
Received a response from Poloniex, they don't calculate compound interest on multi day loans. 
Merged.

**Pull request merged**
