### PR TITLE
Settings improvements

### PR DESCRIPTION
**Pull request by yura-pakhuchiy**
- Move select botlog.json button to settings dialog
- Clicking on label selects control in settings
- Cleanups

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by rnevet** [comment]
@yura-pakhuchiy the only thing that bothers me is that it is now completely not intuitive to find the select file function. 
How about making it a button like settings (that will only be visible when needed) with a modal dialog?

**Comment by yura-pakhuchiy** [comment]
@rnevet Actually selecting file in preferences seems quite intuitive for me, but your idea with new menu item sounds better! Developers might want change log file often, opening settings for this maybe annoying.

**Comment by yura-pakhuchiy** [comment]
@rnevet I pushed commit which implements this

**Comment by rnevet** [comment]
Very nice! 👍

**Pull request merged**
