### PR TITLE
Look up conversion rates from blockchain.info for web server display

### PR DESCRIPTION
**Pull request by laxdog**
Allow people outside the US to get local FIAT currency displayed in the web server. 

## Description
Looks up rates from the blockchain.info ticker and uses them in the botlog.json

Haven't done any of the docs or config for it yet as I wanted to see if it was going to be worth while. 

Just set outputCurrency in the default.cfg to one found here : https://blockchain.info/ticker

## TESTING STAGE
Still testing, was more submitting PR to gauge interest. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] **I have read CONTRIBUTING.md**
- [x] **I fully understand [Github Flow.](https://guides.github.com/introduction/flow/)**
- [x] **My code adheres to the [code style of this project.](https://poloniexlendingbot.readthedocs.io/en/latest/contributing.html)**
- [ ] **I have updated the documentation in /docs if I have changed the config, arguments, logic in how the bot works, or anything that understandably needs a documentation change.**
- [ ] **I have updated the config file accordingly if my change requires a new configuration setting or changes an existing one.**
- [ ] **I have tested the bot with no issues for 24 continuous hours. If issues were experienced, they have been patched and tested again.**

### CODE REVIEW

**Comment by rnevet** [comment]
Nice idea, wouldn't it be easier to use the https://blockchain.info/tobtc?currency=EUR&value=1 api ?

**Comment by laxdog** [comment]
It's the same info, but if I get the full ticker in one go we don't have to hardcode the available values. Thought it might be better that way in case they add more currencies later to avoid code changes on the bot side.

**Comment by rnevet** [comment]
I would say try the currency, if available use value otherwise not.

**Comment by laxdog** [comment]
Ok, I pushed that fix.

**Comment by rnevet** [comment]
Sorry to bother, but thinking about it, we don't want a dependency on the availability of blockchain API, I would suggest to catch all exceptions from that block.

**Comment by laxdog** [comment]
Np, that's a good point that I didn't think about. I'll look at it later. Codacy has a problem too it seems.

**Comment by rnevet** [comment]
Can ignore the codacy issue, it just an advice. But you should rebase onto lending-rewrite.

**Comment by laxdog** [comment]
How do I continue pushing to this PR if I rebase?

**Comment by Evanito** [comment]
You don't *have* to, I can merge this into master at the same time I do #174
It would just be recommended as we can have all the changes on one branch.

**Comment by laxdog** [comment]
I more meant how do I actually do that? Don't I need to raise a new PR on the other branch?

**Comment by Evanito** [comment]
Turns out I could do it the whole time. Just found this documentation. https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

**Comment by Evanito** [comment]
Thank you for contributing!

**Pull request merged**
