### PR TITLE
Output Currency revolution

### PR DESCRIPTION
**Pull request by rnevet**
Display estimated earnings for all lent coins in output currency
Display output currency exchange rate for all lent coins (inspired by @yura-pakhuchiy)
Display total lent for BTC respecting display units (mBTC, Bits, Satoshi) fix comment on https://github.com/Mikadily/poloniexlendingbot/issues/197

## TESTING STAGE
In progress

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] **I have read CONTRIBUTING.md**
- [x] **I fully understand [Github Flow.](https://guides.github.com/introduction/flow/)**
- [x] **My code adheres to the [code style of this project.](https://poloniexlendingbot.readthedocs.io/en/latest/contributing.html)**
- [N/A] **I have updated the documentation in /docs if I have changed the config, arguments, logic in how the bot works, or anything that understandably needs a documentation change.**
- [N/A] **I have updated the config file accordingly if my change requires a new configuration setting or changes an existing one.**
- [x] **I have tested the bot with no issues for 24 continuous hours. If issues were experienced, they have been patched and tested again.**

### CODE REVIEW

**Comment by rnevet** [comment]
@yura-pakhuchiy  what do you think?

**Comment by yura-pakhuchiy** [comment]
@rnevet I'm away from laptop right now. I will try this branch in 2 days and let you know

**Comment by rnevet** [comment]
add the min limit rate to the log when bot decides not to lend. https://github.com/Mikadily/poloniexlendingbot/issues/212

**Comment by yura-pakhuchiy** [comment]
@rnevet Looks good! Few notes:

1.  `1 BTC = 1012.0000 USDT`

Looks like too many zeroes after dot. I think there should be configuration option for output currency precision.

2. I'm not sure that I like all currencies converted to USDT. Would be great to have option which preserves old behavior (all crytptos converted to BTC and only summary converted to output currency)

**Comment by rnevet** [comment]
Thanks, regarding your points,

`1 MAID = 0.1359 EUR` , `1 BTC = 941.0968 EUR` - the more configuration options we are adding, it makes the bot harder to maintain. I could reduce precision to 3 and we can trim zeros on right side. otherwise it doesn't seem to me worth the effort.

**Comment by yura-pakhuchiy** [comment]
I agree with "the more configuration options we are adding, it makes the bot harder to maintain", but there is another side - features makes software useful.

In this particular case, there is no single precision which will suit all possible summary currencies. 2-4 is enough for USD/EUR, but if we display eg., STR in BTC, it is definitely not. 1 STR = 237 satoshi ATM.

This option does not add a lot to maintenance burden, just get one value and pass it to `printFloat` directly without any manipulations. I do not propose to add precision option per every coin user holds, just one option for summary coin.

**Comment by rnevet** [comment]
I actually think it is solvable with logic, something in the direction of show a min of 2 precision and more if value is lower, basically always 2 numbers to the right of the most significant one. What do you think?

**Comment by rnevet** [comment]
Do you have maybe time to implement the switch option that you suggested in 2. ?  Use BTC or Output for inlime coin summary?

**Comment by rnevet** [comment]
@yura-pakhuchiy I think I solved the exchange rate display issue, check it out.

**Comment by rnevet** [comment]
I actually like the prettyFloat(value, 2) display, I think we should use it everywhere...

**Comment by Evanito** [comment]
When set to Bits, I get this exchange rate shown for USDT: `1 Bits = 1041.2000 USDT`

**Comment by rnevet** [comment]
Latest version? As that also doesn't look like pretty Float.

**Comment by Evanito** [comment]
```
pi@evpi:~/poloniexlendingbot $ sudo git branch
* custom_btc_display_unit
  master
pi@evpi:~/poloniexlendingbot $ sudo git pull
Already up-to-date.
```

**Comment by rnevet** [comment]
I'll check. :)

**Pull request merged**
