### PR TITLE
Implemented mass AutoRenew feature, set when bot stops and clear when…

### PR DESCRIPTION
**Pull request by rnevet**
Added ability to automatically switch Active Loans AutoRenew flag when it shuts down and clear the AutoRenew flag when it starts.
Useful if you can't keep the bot running for some reason.
The --clearAutoRenew command line parameter is useful if you want to stop loaning completely.

Both abilities are disabled by default.

### CODE REVIEW

**Comment by Mikadily** [comment]
Nice feature. But not sure if time.sleep(sleepTime) move is necessary. Now if it ends in error it will rapidly retry.

**Comment by Mikadily** [comment]
Oh I understand :) it won't catch a keyboardinterupt exception.

**Comment by Mikadily** [comment]
It could be improved. But as it's disabled by default, won't hurt much. Thanks!

**Comment by rnevet** [comment]
Yeah, I rushed a bit to implement it... in 2nd thought it would be better to just have 2 separate commands (either py files or cl params) for setting/clearing autorenew for all loans. I could make the change if it is useful.

**Comment by rnevet** [comment]
Hmm.. and you are right, a sleep is needed also the exception case.

**Pull request merged**
