### PR TITLE
HOTFIX: Fix wrong function declaration in Console Logger

### PR DESCRIPTION
**Pull request by rnevet**
## Description
Fixes issue https://github.com/Mikadily/poloniexlendingbot/issues/134 where status function in Console Logger is missing a parameter.

## TESTING STAGE
Couldn't test myself.

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] **I have read CONTRIBUTING.md**
- [X] **I fully understand [Github Flow.](https://guides.github.com/introduction/flow/)**
- [X] **My code adheres to the [code style of this project.] (https://poloniexlendingbot.readthedocs.io/en/latest/contributing.html)**
- [x] **I have updated the documentation in /docs if I have changed the config, arguments, logic in how the bot works, or anything that understandably needs a documentation change.**
- [x] **If my change requires a change to the config, I have updated the config file and command line arguments accordingly.**
- [ ] **I have tested the bot with no issues for 24 continuous hours. If issues were experienced, they have been patched and tested again.**

### CODE REVIEW

**Comment by Evanito** [comment]
We don't want to show the days remaining if using console view? 

LGTM

**Comment by rnevet** [comment]
I made a functional fix, do you think it should be displayed?

**Comment by Evanito** [comment]
Console view is too cluttered already, I say merge as-is.

**Comment by Evanito** [comment]
Oh, and sorry for overlooking this in the first place. I always use the botlog so it never came up.

**Pull request merged**
