### PR TITLE
Limit Poloniex API requests to 6 per second

### PR DESCRIPTION
**Pull request by rnevet**
Limit Poloniex API requests to 6 per second
Fix DryRun - was broken.

I couldn't fully test it under my connection, reduced request per sec to 1 and that worked.

Please test, verify and Squash Merge. :)

### CODE REVIEW

**Comment by rnevet** [comment]
Will close issue: https://github.com/Mikadily/poloniexlendingbot/issues/188

**Comment by Evanito** [comment]
!Before we merge!
While the branch is entirely my commits, I want to remove my error handling code because it is out of scope of a "lending rewrite" and is not fully successful.

@rnevet Thoughts?

**Comment by rnevet** [comment]
Fine by me, time out is already handled, #181 isn't solved, this change should prevent the API rate issue.

**Comment by Evanito** [comment]
Had to cherrypick and make some changes to work with the removal of my last two commits.
Consider this merged.

**Comment by rnevet** [comment]
Great.

**Pull request closed without merging**
