### PR TITLE
Display both Lent Total and Lent Lendable only if they are different

### PR DESCRIPTION
**Pull request by yura-pakhuchiy**
## Description
Showing both of them just pollutes screen in case if they are equal.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] **I have read CONTRIBUTING.md**
- [x] **I fully understand [Github Flow.](https://guides.github.com/introduction/flow/)**
- [ ] **My code adheres to the [code style of this project.](https://poloniexlendingbot.readthedocs.io/en/latest/contributing.html)**
- [N/A] **I have updated the documentation in /docs if I have changed the config, arguments, logic in how the bot works, or anything that understandably needs a documentation change.**
- [N/A] **I have updated the config file accordingly if my change requires a new configuration setting or changes an existing one.**
- [ ] **I have tested the bot with no issues for 24 continuous hours. If issues were experienced, they have been patched and tested again.**

### CODE REVIEW

**Comment by yura-pakhuchiy** [comment]
BTW, coding style covers only Python and regular contributors can not set labels (however CONTRIBUTING.md tolds them so)

**Comment by rnevet** [comment]
Great, I wanted to do that.  I'm also thinking if the effective rate calculation needs to be changes to calculated compare to lendable amount and not total - not sure.

**Comment by Evanito** [comment]
Don't worry about it, I would rather @rnevet created the JS style requirements. And I do realise the labels are unable to be set by non-contributors, but they are there to guide everybody.

**Comment by yura-pakhuchiy** [comment]
@rnevet As I told before, it should not depend on lent amount. Problem solved, but you probably will disagree :-)

**Comment by yura-pakhuchiy** [comment]
@Evanito new contributors might lose time trying to figure out how to add labels. I think it should noted that they are not expected to set them.

**Comment by rnevet** [comment]
@yura-pakhuchiy being consistent with your own opinion is a good trait. :) 
We can think about some url params for personal customization of the html.

**Comment by rnevet** [comment]
lgtm

**Comment by rnevet** [comment]
lgtm

**Comment by yura-pakhuchiy** [comment]
> We can think about some url params for personal customization of the html.

@rnevet Sounds good. I will make a patch.

**Pull request merged**
