### PR TITLE
try to fix bug with connection timeout

### PR DESCRIPTION
**Pull request by Kurairaito**
This is an attemp to fix https://github.com/Mikadily/poloniexlendingbot/issues/61

In my case, the bot run on a Synology NAS. When I used download manager (on NAS), (wich take 100% of my bandwith), my bot was sometimes stuck too.

With this fix, I didn't experienced the same issue, but I'm not sure if it correct it completely

### CODE REVIEW

**Comment by Evanito** [comment]
LGTM :+1:

**Comment by rnevet** [comment]
I don't think you should have exception handling inside there.

**Comment by Evanito** [comment]
With the exception handling, won't it log an error saying what went wrong and then continue as normal, instead of causing failure? 
By having the exception set `jsonRet = ""` then we don't have an error where jsonRet is undefined or just mimics the last message.

**Comment by rnevet** [comment]
There is already error handling in the main bot loop, which also includes a sleep so the bot doesn't hammer the server.
Returning "" will, I think, anyway crash the bot but in another place because this isn't a valid response for the request.

**Comment by Evanito** [comment]
Hmm, you are probably right.

Close merge if you are sure.

**Comment by Kurairaito** [comment]
Well on worst case, the bot crash and an other script can relaunch it.
Actually it is stuck at that line and you must monitor output file to see
if it is working or not, then kill it, and relaunch it. Maybe we could just
terminate the process if entering in exception ?

**Comment by rnevet** [comment]
I noticed that you only added the timeout to the private API calls, I created another pull request with a more general solution that adds the timeout on the socket level so all requests are covered.
Here:
https://github.com/Mikadily/poloniexlendingbot/pull/69

**Pull request closed without merging**
