### PR TITLE
Pushbullet Support for Notifications

### PR DESCRIPTION
**Pull request by utdrmac**
## Description
Adds notification support for Pushbullet.com

## TESTING STAGE
Testing done on my own fork to my own device.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] **I have read CONTRIBUTING.md**
- [x] **I fully understand [Github Flow.](https://guides.github.com/introduction/flow/)**
- [x] **My code adheres to the [code style of this project.](https://poloniexlendingbot.readthedocs.io/en/latest/contributing.html)**
- [x] **I have updated the documentation in /docs if I have changed the config, arguments, logic in how the bot works, or anything that understandably needs a documentation change.**
- [x] **I have updated the config file accordingly if my change requires a new configuration setting or changes an existing one.**
- [x] **I have tested the bot with no issues for 24 continuous hours. If issues were experienced, they have been patched and tested again.**

### CODE REVIEW

**Comment by utdrmac** [comment]
As an FYI, the example changes to docs/configuration.rst are not real.

**Comment by laxdog** [comment]
Looks good so far, I'll test it later.

**Comment by laxdog** [comment]
Working well for me. 

Nice job @utdrmac

**Comment by rnevet** [comment]
Great

**Pull request merged**
