### PR TITLE
Catch all HTTP Errors

### PR DESCRIPTION
**Pull request by laxdog**
## Description

Handles more errors from Poloniex correctly, specifically HTTPError and URLError.

Fixes https://github.com/Mikadily/poloniexlendingbot/issues/251 and https://github.com/Mikadily/poloniexlendingbot/issues/257

## TESTING STAGE

Testing now

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] **I have read CONTRIBUTING.md**
- [X] **I fully understand [Github Flow.](https://guides.github.com/introduction/flow/)**
- [X] **My code adheres to the [code style of this project.](https://poloniexlendingbot.readthedocs.io/en/latest/contributing.html)**
- [N/A] **I have updated the documentation in /docs if I have changed the config, arguments, logic in how the bot works, or anything that understandably needs a documentation change.**
- [N/A] **I have updated the config file accordingly if my change requires a new configuration setting or changes an existing one.**
- [ ] **I have tested the bot with no issues for 24 continuous hours. If issues were experienced, they have been patched and tested again.**

### CODE REVIEW

**Comment by laxdog** [comment]
Don't merge this, there's something up. It's not catching what I expected. Need to test a bit more.

**Comment by rnevet** [comment]
Not sure what issue you are facing, but HTTPError is a subclass of URLError if I'm not mistaken so you don't need to check for both.
https://docs.python.org/2/library/urllib2.html#urllib2.URLError

**Comment by rnevet** [comment]
I'm thinking a bit slow on this but I guess we can handle PoloniexApiError the same way.

**Comment by laxdog** [comment]
Yea, you're right:
```
>>> from urllib2 import HTTPError, URLError
>>> isinstance(HTTPError('', '', '', '', None), URLError)
True
```

The issue was that it didn't actually catch it. I put a pdb in after the last else to find out why, but it hasn't happened again yet.

**Comment by laxdog** [comment]
Right finally found it again, looks like it's not catching it because it's on the notifiy_summary thread. So this patch does actually fix https://github.com/Mikadily/poloniexlendingbot/issues/257 , this is just another 422 that can happen on that thread. It'll need a separate patch.

I added the PoloniexApiError to catch and removed the HTTPError in favour of just using URLError. 

Everything should be up to date now.

**Pull request merged**
